import{adminGet,adminAction,admin,adminLogout}from'./admin-data.js';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));let d={};
const nav=[['dashboard','لوحة التحكم'],['students','الطلاب'],['subjects','المواد'],['files','الملفات'],['videos','الفيديوهات'],['quizzes','الاختبارات'],['results','النتائج'],['notifications','الإشعارات'],['supportTickets','الدعم'],['settings','الإعدادات']];
function layout(){const a=admin();if(!a){location.href='admin-login.html';return false}document.querySelector('#app').innerHTML=`<div class="admin-layout"><aside class="sidebar" id="side"><div class="brand"><span class="brand-mark">CA</span><span>Admin</span></div>${nav.map(x=>`<a href="#${x[0]}" data-route="${x[0]}">${x[1]}</a>`).join('')}<a href="#" id="logout">خروج</a></aside><section class="admin-main"><div class="page-title"><div><h1 id="heading">لوحة التحكم</h1><p class="muted">${esc(a.name)} · ${esc(a.role)}</p></div><div class="actions"><button class="btn" id="refresh">تحديث</button><button class="btn" id="menu">☰</button></div></div><div id="view"></div></section></div>`;$('#logout').onclick=e=>{e.preventDefault();adminLogout()};$('#refresh').onclick=()=>load(true);$('#menu').onclick=()=>$('#side').classList.toggle('open');return true}
function arr(x){return x?Object.entries(x).map(([k,v])=>({...(v||{}),_key:k})):[]}
function counts(){return{students:arr(d.students).length,pending:arr(d.students).filter(x=>x.status==='pending').length,files:arr(d.files).length,videos:arr(d.videos).length,quizzes:arr(d.quizzes).length,support:arr(d.supportTickets).filter(x=>x.status!=='closed').length}}
function dashboard(){const c=counts();$('#heading').textContent='لوحة التحكم';$('#view').innerHTML=`<div class="metric-grid">${[['students','إجمالي الطلاب'],['pending','في انتظار الموافقة'],['files','الملفات'],['videos','الفيديوهات'],['quizzes','الاختبارات'],['support','تذاكر مفتوحة']].map(([k,l])=>`<div class="metric"><span class="muted">${l}</span><br><b>${c[k]}</b></div>`).join('')}</div><section class="section"><div class="section-head"><div><h2>إجراءات سريعة</h2></div></div><div class="grid">${[['students','إدارة الطلاب'],['subjects','إضافة مادة'],['files','إضافة ملف'],['videos','إضافة فيديو'],['quizzes','إدارة الاختبارات'],['notifications','إرسال إشعار']].map(x=>`<a class="card" href="#${x[0]}"><div class="icon">＋</div><h3>${x[1]}</h3></a>`).join('')}</div></section>`}
async function section(route){if(route==='dashboard')return dashboard();$('#heading').textContent=nav.find(x=>x[0]===route)?.[1]||route;const list=arr(d[route]);if(route==='students')return renderStudents(list);if(route==='notifications')return renderNotifications(list);if(route==='supportTickets')return renderSupport(list);renderGeneric(route,list)}
function renderStudents(list){const pending=list.filter(x=>x.status==='pending');$('#view').innerHTML=`<div class="toolbar"><input class="field" id="search" placeholder="بحث بالاسم أو الهاتف"></div><div class="table-wrap"><table class="table"><thead><tr><th>الاسم</th><th>الهاتف</th><th>الصف</th><th>الحالة</th><th>إجراءات</th></tr></thead><tbody id="rows">${list.map(x=>`<tr data-text="${esc((x.name||'')+' '+(x.phone||''))}"><td>${esc(x.name)}</td><td>${esc(x.phone)}</td><td>${esc(x.grade)}</td><td><span class="tag ${x.status==='approved'?'ok':x.status==='rejected'?'danger':'gold'}">${esc(x.status)}</span></td><td>${x.status==='pending'?`<button class="btn gold act" data-a="approve" data-id="${x._key}">موافقة</button> <button class="btn danger act" data-a="reject" data-id="${x._key}">رفض</button>`:''}</td></tr>`).join('')}</tbody></table></div>`;bindTable('students')}
function renderGeneric(route,list){$('#view').innerHTML=`<div class="toolbar"><input class="field" id="search" placeholder="بحث..."><button class="btn gold" id="add">＋ إضافة</button></div><div class="grid" id="cards">${list.map(x=>`<article class="card"><span class="tag">${esc(x.term||x.grade||x.type||'محتوى')}</span><h3>${esc(x.title||x.name||x.subject||'عنصر')}</h3><p class="muted">${esc(x.description||x.message||'')}</p><div class="actions"><button class="btn act" data-a="toggle" data-id="${x._key}">${x.published===false?'نشر':'إلغاء النشر'}</button>${admin()?.role==='owner'?`<button class="btn danger act" data-a="delete" data-id="${x._key}">حذف</button>`:''}</div></article>`).join('')||'<div class="empty">لا توجد بيانات.</div>'}</div>`;$('#add').onclick=()=>alert('واجهة الإضافة جاهزة للربط بالنموذج؛ يتم الحفظ عبر admin-action.');bindTable(route)}
function renderNotifications(list){$('#view').innerHTML=`<div class="form-card glass" style="width:100%;margin:0 0 20px"><h2>إرسال إشعار</h2><form id="notify"><div class="group"><label class="label">العنوان</label><input class="field" id="ntitle" required></div><div class="group"><label class="label">الرسالة</label><textarea class="field" id="nmessage" rows="4" required></textarea></div><button class="btn gold">نشر الإشعار</button></form></div><div class="list">${list.map(x=>`<div class="item"><div><b>${esc(x.title)}</b><p class="muted">${esc(x.message)}</p></div></div>`).join('')||'<div class="empty">لا توجد إشعارات.</div>'}</div>`;$('#notify').onsubmit=async e=>{e.preventDefault();try{await adminAction({action:'notify',value:{title:ntitle.value,message:nmessage.value,target:'all',audience:'all'}});await load(true);alert('تم نشر الإشعار')}catch(x){alert(x.message)}}}
function renderSupport(list){$('#view').innerHTML=`<div class="list">${list.map(x=>`<div class="item"><div><b>${esc(x.subject||'دعم')}</b><p class="muted">${esc(x.message||'')}</p><small class="muted">${esc(x.studentKey||'')}</small></div><button class="btn ${x.status==='closed'?'':'gold'} act" data-a="support" data-id="${x._key}" data-val="${x.status==='closed'?'open':'closed'}">${x.status==='closed'?'مغلقة':'إغلاق'}</button></div>`).join('')||'<div class="empty">لا توجد تذاكر.</div>'}</div>`;bindTable('supportTickets')}
function bindTable(route){document.querySelectorAll('.act').forEach(b=>b.onclick=async()=>{try{const a=b.dataset.a;const payload=a==='toggle'?{action:'toggle',path:route,id:b.dataset.id,value:b.textContent.includes('نشر')}:a==='delete'?{action:'delete',path:route,id:b.dataset.id}:a==='support'?{action:'support',id:b.dataset.id,value:b.dataset.val}:{action:a,path:route,id:b.dataset.id};await adminAction(payload);await load(true)}catch(e){alert(e.message)}});$('#search')?.addEventListener('input',e=>document.querySelectorAll('#rows tr,#cards .card').forEach(x=>x.style.display=(x.dataset.text||x.textContent).toLowerCase().includes(e.target.value.toLowerCase())?'':'none'))}
async function load(force=false){try{d=await adminGet();const r=location.hash.slice(1)||'dashboard';await section(r)}catch(e){document.querySelector('#view').innerHTML=`<div class="error">${esc(e.message)}</div>`}}
window.addEventListener('hashchange',()=>load());if(layout())load();
